name: diffuscene
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cython
  - numpy=1.26.4
  - networkx
  - pyrr
  - pyyaml
  - python=3.10
  - pytorch=2.4 
  - pytorch-cuda=12.4
  - torchvision 
  - pillow
  - scipy
  - tqdm
  - trimesh
  - matplotlib
  - wxpython
  - pip:
    - simple_3dviz
    - pytorch-fast-transformers
    - num2words
    - nltk
    - einops_exts
    - kornia
    - rotary_embedding_torch
    - transformers
    - clip
    - pyvista
    - torchtext
    - seaborn
    - wandb
